# Generated by Django 5.2.7 on 2025-10-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactusform'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyTourRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('guests', models.PositiveIntegerField()),
                ('minors', models.PositiveIntegerField(default=0)),
                ('tour_type', models.CharField(default='Standard Historical Tour', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
