# Generated by Django 5.2.7 on 2025-10-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_specialtytourregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('tour_type', models.CharField(default='Standard Historical Tour', max_length=100)),
                ('best_part_message', models.TextField(blank=True)),
                ('length_message', models.TextField(blank=True)),
                ('topics_message', models.TextField(blank=True)),
                ('source_message', models.TextField(blank=True)),
                ('other_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
