# Generated by Django 5.2.7 on 2025-10-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feedback_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='improvement_message',
            field=models.TextField(blank=True),
        ),
    ]
