# Generated by Django 5.2.7 on 2025-10-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
