# Generated by Django 5.2.7 on 2025-10-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_feedback_improvement_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtytourregistration',
            name='time',
            field=models.TimeField(default="12:00:00"),
            preserve_default=False,
        ),
    ]
